### ISSUE TITLE
Page table creation clobbers provided command line

### ISSUE THREAD

**Issue by josephlr** [intel/rust-hypervisor-firmware#10]
Both `cloud-hypervisor` and `firecracker` support passing a command line argument to the image they are launching. The [firmware code in `bzimage.rs`](https://github.com/intel/rust-hypervisor-firmware/blob/073d679d033e8b4d84295c529081d927fb7bef40/src/bzimage.rs#L122-L147) tries to create a command line that consists of:
  - The hypervisor-provided command line, followed by
  - The command line from the on-disk data

However, the provided command line is often at address `0x20000` ([`cloud-hypervisor` example](https://github.com/intel/cloud-hypervisor/blob/e5e651895b73c0fb74f649c182285d63cf97aeb3/vmm/src/config.rs#L18) and [`firecracker` example](https://github.com/firecracker-microvm/firecracker/blob/10fdf2d2c201f9e6b4c5e7c6787a1d63aecfe90c/arch/src/x86_64/layout.rs#L15)). This causes a problem when running [`setup_pagetables()`](https://github.com/intel/rust-hypervisor-firmware/blob/073d679d033e8b4d84295c529081d927fb7bef40/src/main.rs#L59-L72) which writes a single PML3 table at `0xa000` but writes 64 PML2 tables starting at `0xb000`, this will overwrite the command line with garbage, causing either:
  - Nothing to be prepended to the command line when it should
  - Junk to be prepended to the commandline

**Comment by rbradford** [comment]
@josephlr Two solutions come to mind:

1. Find somewhere safe to store the pagetables and just use that
2. Parse the command line very early (delaying expanding the identity mapping) and save anything we need and then clobber anyway.

**Comment by josephlr** [comment]
Fixed by #23 in https://github.com/intel/rust-hypervisor-firmware/commit/de090ed94b382f65db07a1285ca2e5181b79167b
